
package com.math.utility.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.1.5
 * Fri Mar 04 23:37:23 IST 2016
 * Generated source version: 3.1.5
 */

@XmlRootElement(name = "factorial", namespace = "http://utility.math.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "factorial", namespace = "http://utility.math.com/")

public class Factorial {

    @XmlElement(name = "arg0")
    private int arg0;

    public int getArg0() {
        return this.arg0;
    }

    public void setArg0(int newArg0)  {
        this.arg0 = newArg0;
    }

}

