package com.soapclient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.5
 * 2016-02-25T18:06:15.724Z
 * Generated source version: 3.1.5
 * 
 */
@WebService(targetNamespace = "http://utility.math.com/", name = "MathUtility")
@XmlSeeAlso({ObjectFactory.class})
public interface MathUtility {

    @WebMethod
    @RequestWrapper(localName = "factorial", targetNamespace = "http://utility.math.com/", className = "com.soapclient.Factorial")
    @ResponseWrapper(localName = "factorialResponse", targetNamespace = "http://utility.math.com/", className = "com.soapclient.FactorialResponse")
    @WebResult(name = "return", targetNamespace = "")
    public int factorial(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    );

    @WebMethod
    @RequestWrapper(localName = "addIntegers", targetNamespace = "http://utility.math.com/", className = "com.soapclient.AddIntegers")
    @ResponseWrapper(localName = "addIntegersResponse", targetNamespace = "http://utility.math.com/", className = "com.soapclient.AddIntegersResponse")
    @WebResult(name = "return", targetNamespace = "")
    public int addIntegers(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1
    );
}
