package com.soapclient;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.5
 * 2016-02-25T18:06:15.764Z
 * Generated source version: 3.1.5
 * 
 */
@WebServiceClient(name = "MathUtilityService", 
                  wsdlLocation = "file:mathutility.wsdl",
                  targetNamespace = "http://utility.math.com/") 
public class MathUtilityService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://utility.math.com/", "MathUtilityService");
    public final static QName MathUtilityPort = new QName("http://utility.math.com/", "MathUtilityPort");
    static {
        URL url = null;
        try {
            url = new URL("file:mathutility.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(MathUtilityService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:mathutility.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public MathUtilityService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public MathUtilityService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MathUtilityService() {
        super(WSDL_LOCATION, SERVICE);
    }
    




    /**
     *
     * @return
     *     returns MathUtility
     */
    @WebEndpoint(name = "MathUtilityPort")
    public MathUtility getMathUtilityPort() {
        return super.getPort(MathUtilityPort, MathUtility.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MathUtility
     */
    @WebEndpoint(name = "MathUtilityPort")
    public MathUtility getMathUtilityPort(WebServiceFeature... features) {
        return super.getPort(MathUtilityPort, MathUtility.class, features);
    }

}
